import { expect, test } from "./fixtures";
import type { Page } from "@playwright/test";

// What makes the app installable: the manifest index.html points at, the icons that manifest
// points at in turn, and the theme colours the browser paints its own chrome with. All of it is
// static files in public/ and literals in index.html, identical here and in production, so this
// spec runs against the ordinary dev server like every other one.
//
// The service worker is deliberately out of scope. It is generated by `vite build`, and no dev
// server registers one, so there is nothing here to assert against — see vite.config.ts.

interface ManifestIcon {
  src: string;
  sizes: string;
  type: string;
  purpose: string;
}

interface Manifest {
  name: string;
  start_url: string;
  scope: string;
  display: string;
  theme_color: string;
  background_color: string;
  icons: ManifestIcon[];
}

// The app's page background in the given theme, as the `#rrggbb` a manifest and a `<meta>` have
// to spell it. Picked through the real theme control, so this reads the same value a player
// looking at the page would see.
async function pageBackground(page: Page, theme: "Light" | "Dark"): Promise<string> {
  await page.getByRole("radio", { name: theme, exact: true }).click();
  return page.evaluate(() => {
    const value = getComputedStyle(document.documentElement)
      .getPropertyValue("--surface-void")
      .trim();
    // Canvas normalises any CSS colour syntax to `#rrggbb`.
    const probe = document.createElement("canvas").getContext("2d")!;
    probe.fillStyle = value;
    return probe.fillStyle as string;
  });
}

test("the app is installable", async ({ page }) => {
  await page.goto("/");

  const href = await page.locator('link[rel="manifest"]').getAttribute("href");
  expect(href).toBe("/manifest.webmanifest");

  const res = await page.request.get(href!);
  await expect(res).toBeOK();
  expect(res.headers()["content-type"]).toContain("application/manifest+json");

  const manifest = (await res.json()) as Manifest;
  // A browser offers no install at all for a manifest missing any of these.
  expect(manifest).toMatchObject({
    name: "Party",
    start_url: "/",
    scope: "/",
    display: "standalone",
  });

  // Installing needs a 192 and a 512, and the maskable one is what keeps Android from drawing
  // the icon shrunk inside a white circle.
  const bySlot = Object.fromEntries(manifest.icons.map((i) => [`${i.purpose} ${i.sizes}`, i.src]));
  expect(bySlot).toMatchObject({
    "any 192x192": "/icon-192.png",
    "any 512x512": "/icon-512.png",
    "maskable 512x512": "/icon-maskable-512.png",
  });

  // Every icon the manifest names has to actually be there. A file renamed in public/ would
  // otherwise surface only as a blank icon on somebody's home screen.
  for (const icon of manifest.icons) {
    const iconRes = await page.request.get(icon.src);
    expect(iconRes.status(), `${icon.src} is served`).toBe(200);
    expect(iconRes.headers()["content-type"], `${icon.src} content type`).toContain(icon.type);
  }

  // iOS ignores the manifest's icons and takes this one instead.
  const apple = await page.locator('link[rel="apple-touch-icon"]').getAttribute("href");
  expect(apple).toBe("/apple-touch-icon.png");
  expect((await page.request.get(apple!)).status()).toBe(200);

  // The Android splash screen is drawn from these before a single pixel of the app exists, so
  // they have to be the app's own dark background — the theme it opens in by default.
  const dark = await pageBackground(page, "Dark");
  expect(manifest.background_color).toBe(dark);
  expect(manifest.theme_color).toBe(dark);
});

test("the browser chrome is themed for both colour schemes", async ({ page }) => {
  await page.goto("/");

  // index.html cannot read a CSS custom property, so it repeats both `--surface-void` values as
  // literals. This is what catches a change to that token that was not mirrored into them.
  const themeColors = new Map(
    await page
      .locator('meta[name="theme-color"]')
      .evaluateAll((metas) =>
        metas.map((m) => [m.getAttribute("media")!, m.getAttribute("content")!] as const),
      ),
  );

  expect(themeColors.get("(prefers-color-scheme: light)")).toBe(
    await pageBackground(page, "Light"),
  );
  expect(themeColors.get("(prefers-color-scheme: dark)")).toBe(await pageBackground(page, "Dark"));
});
